/* Destination information copied from abha-places-data.xlsx.
   Photography and Adventures tags were approved by the project owner. */
window.ABHA_PLACES = [
  {
    id: "alsoudah",
    nameEn: "ALSOUDAH",
    nameAr: "السودة",
    descriptionEn: "Al Soudah is a beautiful mountain destination known for its cool weather, green landscapes, and breathtaking views.",
    descriptionAr: "السودة وجهة جبلية جميلة تشتهر بأجوائها الباردة، ومناظرها الخضراء، وإطلالاتها الخلابة.",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Al+Soudah%2C+Abha%2C+Saudi+Arabia",
    category: "Nature / طبيعة",
    cost: "100-50 SAR PER PERSON",
    suitableFor: "Family / عائلات • Friends / أصدقاء • Couples / أزواج",
    walking: "High",
    environment: "Outdoor",
    duration: "2-3 HOURS",
    bestTime: "MORNING",
    weatherAlternative: "AL RASHID MALL",
    image: "assets/images/alsoudah.jpg.jpeg",
    approvedTags: ["Photography", "Adventures"]
  },
  {
    id: "tamniah",
    nameEn: "Tamniah",
    nameAr: "تمنية",
    descriptionEn: "Tamniah is a peaceful mountain area surrounded by stunning natural landscapes and beautiful views.",
    descriptionAr: "تمنية منطقة جبلية هادئة تحيط بها المناظر الطبيعية الجميلة والإطلالات الرائعة.",
    mapUrl: "https://maps.app.goo.gl/nBTXQSixr8nGzoFK6?g_st=iw",
    category: "Nature / طبيعة • Relaxation / استرخاء",
    cost: "100-50 SAR PER PERSON",
    suitableFor: "Families / عائلات • Friends / أصدقاء • Couples / أزواج • Nature Lovers / محبو الطبيعة",
    walking: "High",
    environment: "Outdoor",
    duration: "2-3 HOURS",
    bestTime: "MORNING",
    weatherAlternative: "LE PREMIER",
    image: "assets/images/tamniah.jpg.jpg",
    approvedTags: ["Photography", "Adventures"]
  },
  {
    id: "rijal-almaa",
    nameEn: "Rijal Almaa",
    nameAr: "رجال ألمع",
    descriptionEn: "Rijal Almaa is a historic village famous for its traditional stone buildings, rich heritage, and unique architecture.",
    descriptionAr: "رجال ألمع قرية تاريخية تشتهر بمبانيها الحجرية التقليدية، وتراثها الغني، وعمارتها المميزة.",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Rijal+Alma%2C+Asir%2C+Saudi+Arabia",
    category: "Heritage / تراث • Culture / ثقافة",
    cost: "100-300SAR PER PERSON",
    suitableFor: "Families / عائلات • Friends / أصدقاء • History Lovers / محبو التاريخ • Culture Lovers / محبو الثقافة",
    walking: "High",
    environment: "Outdoor",
    duration: "3-4 HOURS",
    bestTime: "MORNING",
    weatherAlternative: "ABU KHAYAL PARK",
    image: "assets/images/rijal-almaa.jpg.jpeg",
    approvedTags: ["Photography"]
  },
  {
    id: "art-street",
    nameEn: "Art Street",
    nameAr: "شارع الفن",
    descriptionEn: "Art Street is a lively cultural destination filled with art, colorful decorations, cafés, and creative spaces.",
    descriptionAr: "شارع الفن وجهة ثقافية حيوية مليئة بالفنون والزخارف الملونة والمقاهي والمساحات الإبداعية.",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Art+Street%2C+Abha%2C+Saudi+Arabia",
    category: "Art / فن • Culture / ثقافة • Family / عائلات",
    cost: "100-300SAR PER PERSON",
    suitableFor: "Families / عائلات • Friends / أصدقاء • Couples / أزواج • Art Lovers / محبو الفن",
    walking: "Moderate",
    environment: "Outdoor",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "AL RASHID MALL",
    image: "assets/images/art-street.jpg.jpg",
    approvedTags: ["Photography"]
  },
  {
    id: "seven",
    nameEn: "SEVEN",
    nameAr: "سفن",
    descriptionEn: "SEVEN is a modern entertainment destination offering a variety of experiences, activities, and places to enjoy.",
    descriptionAr: "سفن وجهة ترفيهية حديثة تقدم مجموعة متنوعة من التجارب والأنشطة والأماكن الممتعة.",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=SEVEN%2C+Abha%2C+Saudi+Arabia",
    category: "Entertainment / ترفيه • Family / عائلات",
    cost: "100-1000 SAR",
    suitableFor: "Families / عائلات • Children / أطفال • Teenagers / مراهقون • Friends / أصدقاء",
    walking: "High",
    environment: "MIXED",
    duration: "2-3 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "HIGH CITY",
    image: "assets/images/seven.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "high-city",
    nameEn: "HIGH CITY",
    nameAr: "المدينة العالية",
    descriptionEn: "HIGH City is a popular destination offering beautiful views, restaurants, cafés, and a relaxing atmosphere.",
    descriptionAr: "المدينة العالية وجهة شهيرة توفر إطلالات جميلة ومطاعم ومقاهي وأجواء هادئة ومريحة.",
    mapUrl: "https://maps.google.com/?q=%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9+%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%8A%D8%A9+%D8%A3%D8%A8%D9%87%D8%A7",
    category: "Restaurants / مطاعم • Cafés / مقاهي • Views / إطلالات",
    cost: "100-500SAR",
    suitableFor: "Families / عائلات • Couples / أزواج • Friends / أصدقاء • Food Lovers / محبو الطعام",
    walking: "Moderate",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "AL RASHID MALL",
    image: "assets/images/high-city.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "abu-khayal-park",
    nameEn: "Abu Khayal Park",
    nameAr: "حديقة أبو خيال",
    descriptionEn: "Abu Khayal Park is a peaceful green space with beautiful views, walking areas, and a relaxing atmosphere.",
    descriptionAr: "حديقة أبو خيال مساحة خضراء هادئة تتميز بإطلالات جميلة وأماكن للمشي وأجواء مريحة.",
    mapUrl: "https://maps.google.com/?q=%D8%AD%D8%AF%D9%8A%D9%82%D8%A9+%D8%A3%D8%A8%D9%88+%D8%AE%D9%8A%D8%A7%D9%84+%D8%A3%D8%A8%D9%87%D8%A7",
    category: "Nature / طبيعة • Family / عائلات • Relaxation / استرخاء",
    cost: "100-200 SAR",
    suitableFor: "Families / عائلات • Children / أطفال • Couples / أزواج • Nature Lovers / محبو الطبيعة",
    walking: "Moderate",
    environment: "Outdoor",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "ART STREET",
    image: "assets/images/abu-khayal-park.jpg.jpeg",
    approvedTags: ["Photography"]
  },
  {
    id: "le-premier",
    nameEn: "Le Premier",
    nameAr: "مجمع لي بريمير",
    descriptionEn: "Le Premier is a modern destination with stylish cafés, restaurants, and a pleasant atmosphere for visitors.",
    descriptionAr: "مجمع لي بريمير وجهة عصرية تضم مقاهي ومطاعم أنيقة وأجواء ممتعة للزوار.",
    mapUrl: "https://maps.google.com/?q=%D9%85%D8%AC%D9%85%D8%B9+%D9%84%D9%8A+%D8%A8%D8%B1%D9%8A%D9%85%D9%8A%D8%B1+%D8%A3%D8%A8%D9%87%D8%A7",
    category: "Shopping / تسوق • Restaurants / مطاعم • Cafés / مقاهي",
    cost: "200-700SAR",
    suitableFor: "Families / عائلات • Couples / أزواج • Friends / أصدقاء • Food Lovers / محبو الطعام",
    walking: "Moderate",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "HIGH CITY",
    image: "assets/images/le-premier.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "al-rashid-mall",
    nameEn: "Al Rashid Mall",
    nameAr: "الراشد مول",
    descriptionEn: "Al Rashid Mall is a popular shopping destination with a wide range of stores, restaurants, and entertainment options.",
    descriptionAr: "الراشد مول وجهة تسوق شهيرة تضم مجموعة واسعة من المتاجر والمطاعم وخيارات الترفيه.",
    mapUrl: "https://maps.google.com/?q=%D8%A7%D9%84%D8%B1%D8%A7%D8%B4%D8%AF+%D9%85%D9%88%D9%84+%D8%A3%D8%A8%D9%87%D8%A7",
    category: "Shopping / تسوق • Entertainment / ترفيه • Family / عائلات",
    cost: "200-3000SAR",
    suitableFor: "Families / عائلات • Children / أطفال • Teenagers / مراهقون • Friends / أصدقاء",
    walking: "High",
    environment: "Indoor",
    duration: "2-3 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "AL ABU SURAH PALACES",
    image: "assets/images/al-rashid-mall.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "al-abu-surah-palaces",
    nameEn: "AL ABU Surah Palaces",
    nameAr: "قصور آل أبو سراح",
    descriptionEn: "Al Abu Surah Palaces is a historic heritage destination featuring traditional Asiri architecture, cultural spaces, cafés, and beautiful mountain views.",
    descriptionAr: "قصور آل أبو سراح وجهة تراثية تاريخية تتميز بالعمارة العسيرية التقليدية والمساحات الثقافية والمقاهي والإطلالات الجبلية الجميلة.",
    mapUrl: "https://maps.google.com/?q=%D9%82%D8%B5%D9%88%D8%B1+%D8%A2%D9%84+%D8%A8%D9%88+%D8%B3%D8%B1%D8%A7%D8%AD+%D8%B1%D8%AC%D8%A7%D9%84+%D8%A3%D9%84%D9%85%D8%B9+%D8%B9%D8%B3%D9%8A%D8%B1",
    category: "Heritage / تراث • Culture / ثقافة • History / تاريخ • Restaurants & Cafés / مطاعم ومقاهي",
    cost: "200-500SAR",
    suitableFor: "Families / عائلات • Friends / أصدقاء • Couples / أزواج • History Lovers / محبو التاريخ • Culture Lovers / محبو الثقافة",
    walking: "Moderate",
    environment: "MIXED",
    duration: "2-3 HOURS",
    bestTime: "MORNING",
    weatherAlternative: "SEVEN",
    image: "assets/images/al-abu-surah-palaces.jpg.jpeg",
    approvedTags: ["Photography"]
  },
  {
    id: "row",
    nameEn: "ROW",
    nameAr: "مقهى روو",
    descriptionEn: "ROW is a modern café offering a cozy atmosphere, specialty coffee, and a selection of sweet treats.",
    descriptionAr: "مقهى روو مقهى عصري يوفر أجواء مريحة وقهوة مختصة ومجموعة متنوعة من الحلويات.",
    mapUrl: "https://maps.app.goo.gl/9iitPShxeLRugxwN9?g_st=iw",
    category: "Café / مقهى • Coffee / قهوة • Desserts / حلويات",
    cost: "10-200SAR",
    suitableFor: "Families / عائلات • Friends / أصدقاء • Couples / أزواج • Coffee Lovers / محبو القهوة",
    walking: "Minimal",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "No change needed",
    image: "assets/images/row.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "hayez",
    nameEn: "Hayez",
    nameAr: "مقهى حيز",
    descriptionEn: "Hayez is a welcoming café offering freshly prepared coffee, baked treats, and a comfortable atmosphere.",
    descriptionAr: "حيز مقهى مميز يقدم القهوة الطازجة والمخبوزات وأجواء مريحة للزوار.",
    mapUrl: "https://maps.app.goo.gl/BMm9hcGHxtyDNk8E9?g_st=iw",
    category: "Café / مقهى • Bakery / مخبوزات • Coffee / قهوة",
    cost: "10-200SAR",
    suitableFor: "Families / عائلات • Friends / أصدقاء • Coffee Lovers / محبو القهوة • Food Lovers / محبو الطعام",
    walking: "Minimal",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "No change needed",
    image: "assets/images/hayez.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "black-by-location",
    nameEn: "Black By Location",
    nameAr: "بلاك باي لوكيشن",
    descriptionEn: "Black Location is a specialty coffee café offering carefully prepared drinks in a modern and inviting setting.",
    descriptionAr: "مقهى للقهوة المختصة يقدم مشروبات محضرة بعناية في أجواء عصرية.",
    mapUrl: "https://maps.app.goo.gl/JEzQQrWQQdYH3nfg8?g_st=iw",
    category: "Specialty Coffee / قهوة مختصة • Café / مقهى",
    cost: "10-200SAR",
    suitableFor: "Friends / أصدقاء • Couples / أزواج • Coffee Lovers / محبو القهوة",
    walking: "Minimal",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "No change needed",
    image: "assets/images/black-by-location.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "lantico",
    nameEn: "L’antico",
    nameAr: "مطعم لانتيكو",
    descriptionEn: "L’antico is an Italian restaurant offering classic Italian dishes, pizza, and a warm dining experience.",
    descriptionAr: "لانتيكو مطعم إيطالي يقدم الأطباق الإيطالية الكلاسيكية والبيتزا وتجربة طعام دافئة.",
    mapUrl: "https://maps.app.goo.gl/GUpnuN3AJuu6Y3aW8?g_st=iw",
    category: "Italian / إيطالي • Pizza / بيتزا • Restaurant / مطعم",
    cost: "50-500SAR",
    suitableFor: "Families / عائلات • Couples / أزواج • Friends / أصدقاء • Food Lovers / محبو الطعام",
    walking: "Minimal",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "No change needed",
    image: "assets/images/lantico.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "curo",
    nameEn: "curo",
    nameAr: "كيرو",
    descriptionEn: "Curo is a modern restaurant offering a variety of delicious dishes in a comfortable and welcoming atmosphere.",
    descriptionAr: "كيرو مطعم عصري يقدم مجموعة متنوعة من الأطباق اللذيذة في أجواء مريحة ومرحبة.",
    mapUrl: null,
    category: "Restaurant / مطعم • Food / مأكولات",
    cost: "50-500SAR",
    suitableFor: "Families / عائلات • Friends / أصدقاء • Couples / أزواج • Food Lovers / محبو الطعام",
    walking: "Minimal",
    environment: "MIXED",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "No change needed",
    image: "assets/images/curo.jpg.jpeg",
    approvedTags: []
  },
  {
    id: "red-basil",
    nameEn: "Red Basil",
    nameAr: "ريد بازل",
    descriptionEn: "Red Basil is an Italian restaurant specializing in Neapolitan-style pizza and flavorful Italian dishes.",
    descriptionAr: "ريد بازل مطعم إيطالي يقدم البيتزا النابولية والأطباق الإيطالية المتنوعة في أجواء مريحة ومميزة.",
    mapUrl: "https://maps.app.goo.gl/XADwyn5Wku42Ba4Y7?g_st=iw",
    category: "Neapolitan Italian / إيطالي نابولي • Pizza / بيتزا • Restaurant / مطعم",
    cost: "50-500SAR",
    suitableFor: "Families / عائلات • Couples / أزواج • Friends / أصدقاء • Food Lovers / محبو الطعام",
    walking: "Minimal",
    environment: "Indoor",
    duration: "1-2 HOURS",
    bestTime: "EVENING",
    weatherAlternative: "No change needed",
    image: "assets/images/red-basil.jpg.jpeg",
    approvedTags: []
  }
];

window.ABHA_EXAMPLE_PREFERENCES = {
  traveler: "Family",
  interest: ["Nature"],
  time: "Half day",
  budget: "100–300 SAR",
  walking: "Moderate"
};
